### PR TITLE
Add support for exclusive add and update operations on sets

### PR DESCRIPTION
**Pull request by waikikamoukow**
This PR adds support for exclusive add and update commands on `Map` data. `Add` commands will attempt to add a new value, but if the key already exists the operation will fail. `Update` commands will attempt to update an existing value, but if the key does not exist the operation will fail. Under the hood this uses the `NX` and `XX` modes for the `set` command in redis (with some equivalent logic added to `MemoryStore`).

Tests have been added to cover these new scenarios, as well as some modifications to fix an issue I was having when testing using ioredis-mock (most notably forcibly flushing the redis database when resolving to solve an issue where I was getting data from a previous test still present in redis in subsequent tests). I've also updated the tests to utilise ioredis-mock instead of MemoryStore (not sure if instead this should be set up to run the tests for both?)

### CODE REVIEW

**Comment by sinclairzx81** [comment]
@waikikamoukow Hi! :)

Happy to roll this through, but would it be possible to use an `options` argument on `set` that allows the caller to specify the `set` condition (potentially leaving room for other options in future (like TIL))? This just helps keep things umbrella'ed under the `set` operation rather than having alias methods like `add()`, `update()` and `setNew()`.

### Usage

The following would be the usage.

```typescript
map.set(key, value)                       // default                                
map.set(key, value, { if: 'not-exists' }) // map.add(key, value)    > NX
map.set(key, value, { if: 'exists' })     // map.update(key, value) > XX
```
### Store Interface

The Store interface should only expose a subset of actual redis operations (as they would be named in drivers like `io-redis` as well as redis itself). So just need to ensure this interface is kept alias free. The following is a small update to the store interface to include the `SetOptions` argument on `set`; and leaves room for additional options to be setup for some of the other operators in future.  

```typescript
export interface SetOptions { // NEW
  if?: 'exists' | 'not-exists'  // XX | NX respectively
}

export interface Store {
  del(key: string): Promise<void>
  llen(key: string): Promise<number>
  lset(key: string, index: number, value: string): Promise<void>
  lindex(key: string, index: number): Promise<string | null>
  rpush(key: string, value: string): Promise<void>
  lpush(key: string, value: string): Promise<void>
  rpop(key: string): Promise<string | null>
  lpop(key: string): Promise<string | null>
  lrange(key: string, start: number, end: number): Promise<string[]>
  get(key: string): Promise<string | null>
  keys(pattern: string): Promise<string[]>
  exists(key: string): Promise<number>
  expire(key: string, seconds: number): Promise<void>
  set(key: string, value: string, options?: SetOptions): Promise<void> // UPDATE
  disconnect(): void
}
```
### Set() Implementation

The following is a draft implementation for the `set` function (both Redis and Memory). I note, the `throw` on failed condition is a little bit above and beyond (where a condition could simply be a `noop` (with a boolean return result indicating the operation occurred)), but happy to go with the throw logic on this PR.

```typescript
  // RedisStore
  public async set(key: string, value: string, options: SetOptions = {}): Promise<void> {
    if (options.if === 'not-exists') {
      const result = await this.redis.set(key, value, 'NX')
      if (!result) throw new Error('Key already exists')
    } else if (options.if === 'exists') {
      const result = await this.redis.set(key, value, 'XX')
      if (!result) throw new Error('Key does not exist')
    } else {
      await this.redis.set(key, value)
    }
  }

  // MemoryStore
  public async set(key: string, value: string, options: SetOptions = {}): Promise<void> {
    if (options.if === 'not-exists') {
      if (this.#data.has(key)) throw new Error('Key already exists')
      this.#data.set(key, value)
    } else if (options.if === 'exists') {
      if (!this.#data.has(key)) throw new Error('Key does not exist')
      this.#data.set(key, value)
    } else {
      this.#data.set(key, value)
    }
  }
```
Open to thoughts on the above. Mostly the goal here is to try and keep the `Store` interface 1-1 with known Redis ops (and avoid adding new alias names for command options already defined by Redis). This just makes it easier to port to other redis drivers (or other KV stores) in future.

**Comment by sinclairzx81** [comment]
@waikikamoukow Btw, would you like to be added as a collaborator on this repo? Can send you an invite if you're interested :)

**Comment by waikikamoukow** [comment]
Thanks for the feedback @sinclairzx81 - I've made some modifications based on your notes. I've started looking into implementing some of the other options on ioredis as well, and came across a scenario where the `MemoryStore` currently behaves differently to redis. I'll create separate PRs for those though. 

I'd also be happy to be added as a collaborator on the repo :)

**Comment by sinclairzx81** [comment]
@waikikamoukow Hey! Thanks for updating those. The changes look good, so will roll them through shortly :)

Cheers!
S

**Comment by sinclairzx81** [comment]
@waikikamoukow Updates published on `0.12.6` (all packages update as a set)

Also, have sent you through a collaborator invite, this should come through on email. Let me know if you received ok :)

Cheers mate!
S

**Pull request merged**
